# Generated by Django 3.2.5 on 2023-12-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20231209_1024'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PluginModel',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='tarif',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='course.course'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Wait for payment'), (2, 'Payed')], default=0),
        ),
        migrations.DeleteModel(
            name='TarifModel',
        ),
    ]
