# Generated by Django 3.2.5 on 2023-12-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20231208_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age13_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='age16_90',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='age6_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='profi',
            field=models.BooleanField(default=False),
        ),
    ]
