# Generated by Django 3.2.5 on 2023-12-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20231208_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('score_from', models.IntegerField()),
                ('score_to', models.IntegerField()),
                ('picture', models.URLField(blank=True, null=True)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
