# Generated by Django 3.2.5 on 2023-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_userlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
