# Generated by Django 3.2.5 on 2023-12-09 14:23

import authorization.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorization', '0005_users_total_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authcodemodel',
            options={'verbose_name': 'Код авторизации', 'verbose_name_plural': 'Коды авторизации'},
        ),
        migrations.AlterModelOptions(
            name='userlevel',
            options={'verbose_name': 'База знаний', 'verbose_name_plural': 'Базы знаний'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tg_chat_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tg_chat_start_link',
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='color',
            field=models.CharField(max_length=255, verbose_name='Цвет (hex)'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.CharField(max_length=255, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='score_from',
            field=models.IntegerField(verbose_name='Нижний порог'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='score_to',
            field=models.IntegerField(verbose_name='Верхний порог'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age13_16',
            field=models.BooleanField(default=False, verbose_name='Категория 13-16'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age16_90',
            field=models.BooleanField(default=False, verbose_name='Категория 16-90'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age6_12',
            field=models.BooleanField(default=False, verbose_name='Категория 6-12'),
        ),
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female')], default='unknown', max_length=64, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Пользователь подтвержден'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя юзера'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=255, null=True, validators=[authorization.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profi',
            field=models.BooleanField(default=False, verbose_name='В профи'),
        ),
        migrations.AlterField(
            model_name='users',
            name='refresh_token',
            field=models.TextField(verbose_name='Рефреш токен'),
        ),
        migrations.AlterField(
            model_name='users',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Общая сумма баллов'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.Permission', verbose_name='Доступы пользователя'),
        ),
    ]
