# Generated by Django 3.2.5 on 2023-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20231209_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='initial_passed',
            field=models.BooleanField(default=False),
        ),
    ]
