# Generated by Django 3.2.5 on 2023-12-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cstests', '0004_alter_variantmodel_is_right'),
        ('banners', '0003_bannermodel_for_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('educational_text', models.TextField(blank=True, null=True)),
                ('generated_tests', models.TextField(blank=True, null=True)),
                ('sources', models.ManyToManyField(to='banners.SourceModel')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cstests.cstestmodel')),
            ],
        ),
    ]
