# Generated by Django 3.2.5 on 2023-12-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.URLField(blank=True, null=True),
        ),
    ]
