# Generated by Django 3.2.5 on 2023-12-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cstests', '0009_auto_20231209_1423'),
        ('banners', '0004_auto_20231209_1423'),
        ('course', '0003_auto_20231209_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_template',
            field=models.URLField(blank=True, null=True, verbose_name='Шаблон сертификата'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='educational_text',
            field=models.TextField(blank=True, null=True, verbose_name='Обучающий текст'),
        ),
        migrations.AlterField(
            model_name='course',
            name='generated_tests',
            field=models.TextField(blank=True, null=True, verbose_name='Сгенерированные вопросы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sources',
            field=models.ManyToManyField(blank=True, to='banners.SourceModel', verbose_name='Обучающие материалы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cstests.cstestmodel', verbose_name='Связанный тест'),
        ),
    ]
