# Generated by Django 3.2.5 on 2023-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20231209_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='for_age',
            field=models.CharField(choices=[('6-12+', '6-12+'), ('13-16+', '13-16+'), ('16-90+', '16-90+')], default='16-90+', max_length=256, verbose_name='Для возрастной категории'),
        ),
    ]
