# Generated by Django 3.2.5 on 2023-12-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_for_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profi',
            field=models.BooleanField(default=False),
        ),
    ]
