name: hotel_writer
description: A Flutter project for profession-it.  TeamForWin team.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  dio: ^5.3.3
  auto_route: ^7.8.4
  elementary: ^2.0.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  pinput: ^3.0.1
  intl: ^0.18.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  retrofit: ^4.0.3
  flutter_svg: ^2.0.8
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  url_launcher: ^6.1.14
  decimal: ^2.3.3
  webview_flutter: ^4.4.1
  google_maps_flutter: ^2.5.0
  google_maps_cluster_manager: ^3.0.0+1
  rxdart: ^0.27.3
  flutter_markdown: ^0.6.14
  dadata_suggestions:
    git:
      url: https://github.com/AurelVU/dadata_suggestions.git
      ref: null_saffety
  firebase_crashlytics: ^3.4.2
  firebase_core: ^2.20.0
  firebase_analytics: ^10.6.2
  firebase_performance: ^0.9.3+2
  easy_debounce: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+3
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/images/products.png
    - assets/images/farmer.png
