version: '3.7'

services:

  es:
    build: .
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=nikpasswd # password for default user: elastic
      - xpack.security.enabled=true

    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    stdin_open: true
    tty: true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 2000m
        max-file: "3"

volumes:
  elasticsearch:
