# Generated by Django 3.2.5 on 2023-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cstestmodel',
            name='complexity',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=256, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='cstestmodel',
            name='for_age',
            field=models.CharField(choices=[('6-12+', '6-12+'), ('13-16+', '13-16+'), ('16-90+', '16-90+')], default='16-90+', max_length=256, verbose_name='Для возраста'),
        ),
        migrations.AddField(
            model_name='cstestmodel',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cstestmodel',
            name='topic',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='explain_answer',
            field=models.CharField(default=' ', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='type',
            field=models.CharField(choices=[('single_checked', 'Один верный'), ('multiple_checked', 'Много верных вариантов'), ('text', 'Текстовый ответ')], default='single_checked', max_length=256),
        ),
        migrations.AddField(
            model_name='variantmodel',
            name='right_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
