# Generated by Django 3.2.5 on 2023-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstests', '0002_auto_20231208_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantmodel',
            name='right_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
