# Generated by Django 3.2.5 on 2023-12-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstests', '0003_alter_variantmodel_right_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantmodel',
            name='is_right',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
