# Generated by Django 3.2.5 on 2023-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstests', '0006_alter_testresults_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='app_score',
            field=models.IntegerField(default=0),
        ),
    ]
