# Generated by Django 3.2.5 on 2023-12-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstests', '0007_testresults_app_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='explain_answer',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='sort_number',
            field=models.IntegerField(default=0),
        ),
    ]
