# Generated by Django 3.2.5 on 2023-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstests', '0009_auto_20231209_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantmodel',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='Является правильным'),
        ),
    ]
