# Generated by Django 3.2.5 on 2023-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstests', '0011_alter_cstestmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cstestmodel',
            name='profi',
            field=models.BooleanField(default=False),
        ),
    ]
