# Generated by Django 3.2.5 on 2023-12-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('title', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('profi', models.BooleanField(default=False)),
                ('for_age', models.CharField(choices=[('6-12+', '6-12+'), ('13-16+', '13-16+'), ('16-90+', '16-90+')], default='16-90+', max_length=256)),
            ],
        ),
    ]
