# Generated by Django 3.2.5 on 2023-12-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_sourcemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='for_age',
            field=models.CharField(choices=[('6-12+', '6-12+'), ('13-16+', '13-16+'), ('16-90+', '16-90+')], default='16-90+', max_length=256),
        ),
    ]
