# Generated by Django 3.2.5 on 2023-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
        ('banners', '0003_bannermodel_for_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='sourcemodel',
            options={'verbose_name': 'База знаний', 'verbose_name_plural': 'Базы знаний'},
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='for_age',
            field=models.CharField(choices=[('6-12+', '6-12+'), ('13-16+', '13-16+'), ('16-90+', '16-90+')], default='16-90+', max_length=256, verbose_name='Для возрастной категории'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='image_url',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='banner_pictures', to='pictures.PictureModel', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='link',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='Порядок в очереди'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст баннера'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='type',
            field=models.CharField(choices=[('imageBanner', 'картинка'), ('buttonBanner', 'кнопка'), ('titleBanner', 'заголовок'), ('markdownBanner', 'markdown'), ('sliderBanner', 'слайдер')], default='image', max_length=256, verbose_name='Тип баннера'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='for_age',
            field=models.CharField(choices=[('6-12+', '6-12+'), ('13-16+', '13-16+'), ('16-90+', '16-90+')], default='16-90+', max_length=256, verbose_name='Для возрастной категории'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='profi',
            field=models.BooleanField(default=False, verbose_name='Профи'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='Ссылка'),
        ),
    ]
